[options]
admin_passwd = admin_master_password

db_host = db
db_port = 5432
db_user = odoo_admin
db_password = YourStrongPassword123!

addons_path = /mnt/extra-addons,/mnt/extra-addons-custom

log_level = info
